
# in project root:
#   docker-compose -p generic-fse up -d
#   clear && docker ps
#   docker-compose stop

# clear && docker-compose up -d && clear && docker ps
# clear && docker-compose stop

# https://dashboard.heroku.com/apps/sleepy-mesa-01616/deploy/heroku-container

version: "3.8"

services:
  authserver:
    container_name: generic-fse-authserver
    build: 
      context: authserver
      dockerfile: Dockerfile
    env_file: 
      - authServer/.env
    ports:
      - 4500:4500
  backend:
    container_name: generic-fse-backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: 
      - backend/.env
    ports:
      - 5000:5000
  frontend:
    container_name: generic-fse-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: 
      - frontend/.env
    ports:
      - 3000:3000