
# in project root:
#   docker-compose up -d
#   clear && docker ps
#   docker-compose stop

version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: 
      - backend/.env
    ports:
      - 5000:5000
  authserver:
    build: 
      context: authserver
      dockerfile: Dockerfile
    env_file: 
      - authServer/.env
    ports:
      - 4500:4500
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: 
      - frontend/.env
    ports:
      - 3000:3000